# Generated by Django 5.2.7 on 2025-10-18 19:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_validacao",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("data_emissao", models.DateTimeField(auto_now_add=True)),
                (
                    "arquivo_pdf",
                    models.FileField(blank=True, null=True, upload_to="certificados/"),
                ),
            ],
            options={
                "verbose_name": "Certificado",
                "verbose_name_plural": "Certificados",
                "db_table": "certificado",
            },
        ),
    ]
