# Generated by Django 5.2.7 on 2025-10-18 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("certificados", "0001_initial"),
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificado",
            name="inscricao",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificado",
                to="eventos.inscricao",
            ),
        ),
    ]
